services:
  db:
    image: postgres:15
    container_name: transport-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: transport
      TZ: UTC
    ports:
      - '5432:5432'

  app:
    build: .
    container_name: transport-api
    depends_on:
      db:
        condition: service_started
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/transport
      FIXER_API_KEY: your_fixer_key_here
      API_KEY: local-dev-key
      OPENSSL_CONF: /dev/null
    command: sh -c " sleep 10 && npx prisma generate && npx prisma migrate deploy && npm run seed && npm run dev"
